/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ejemplo.h"
#include <stdio.h>
/*Define la cabecera del procedimiento remoto*/
/*Los parametros se reciben en *argp*/
int * nllamadas_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	result=result+1;

	return &result;
}

//Implementamos el conexion1.
char ** conexion_1_svc(char **argp, struct svc_req *rqstp){
	static char * result;
	char cadena[50];
	static int contador;
	contador = contador+1;

	sprintf(cadena, "El usuario %s se ha conectado %d\n",*argp,contador);
	result = strdup(cadena);
	return &result;
}
