/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJEMPLO_H_RPCGEN
#define _EJEMPLO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define NPROG 0x20000001
#define NVERS0 1

#if defined(__STDC__) || defined(__cplusplus)
#define nllamadas 1

extern  int * nllamadas_1(void *, CLIENT *);
extern  int * nllamadas_1_svc(void *, struct svc_req *);
extern int nprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define nllamadas 1
extern  int * nllamadas_1(); /*En el stub del cliente se usa ese nombre. El 1 ese es 1 porque es el num de poc de le hemos puesto*/
extern  int * nllamadas_1_svc(); /*En el stub del servidor se usa ese nombre*/
extern int nprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJEMPLO_H_RPCGEN */
